version: 2.1

orbs:
  heroku: circleci/heroku@1.0.1

workflows:
  build_test_deploy:
    jobs:
      - build
      - test:
          requires:
            - build
      - deploy-staging:
          filters:
            branches:
              only:
                - staging
          requires:
            - test
      - deploy-master:
          filters:
            branches:
              only:
                - master
          requires:
            - test

jobs:
  build:
    docker:
      - image: node:latest
    working_directory: ~/cuc-to-api
    steps:
      - checkout
      - run: npm install
      - save_cache:
          key: v1-cuc-to-api-cache
          paths:
            - ~/node_modules
  test:
    docker:
      - image: node:latest
    working_directory: ~/cuc-to-api
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-cuc-to-api-cache
      - run: npm test
  deploy-staging:
    environment:
      app_name: cuc-to-staging
    executor: heroku/default
    steps:
      - checkout
      - heroku/install
      - heroku/deploy-via-git:
  deploy-master:
    environment:
      app_name: cuc-to
    executor: heroku/default
    steps:
      - checkout
      - heroku/install
      - heroku/deploy-via-git:
