version: 2.1

orbs:
  heroku: circleci/heroku@1.0.1

workflows:
  heroku_deploy:
    jobs:
      - build
      - test:
          requires:
            - build
      - heroku/deploy-via-git:
          requires:
            - test
          filters:
            branches:
              only: staging
          environment:
            app-name: cuc-to-staging
      - heroku/deploy-via-git:
          requires:
            - test
          filters:
            branches:
              only: master
          environment:
            app-name: cuc-to
jobs:
  build:
    docker:
      - image: node:latest
    working_directory: ~/repo
    steps:
      - checkout
      - run: npm install
      - save_cache:
          key: v1-cuc-to-api-cache
          paths:
            - /node_modules
  test:
    docker:
      - image: node:latest
    working_directory: ~/repo
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-cuc-to-api-cache
      - run: npm test